#ifndef _RESULT_DEFINE_H_
#define _RESULT_DEFINE_H_

enum LOGIN_RESULT
{
	LOGINR_SUCCESS = 1,			//
	LOGINR_AUTH_FAIL,			//验证失败
	LOGINR_VERSION_FAIL,		//版本错误
	LOGINR_STOP_SERVICE,		//暂时停止服务
	LOGINCR_FULL,				//Login满
	LOGINCR_STOP_SERVICE,		//暂时停止服务
};

enum ASKCREATEDB_RESULT
{
	ASKCREATEDBR_SUCCESS,			//
	ASKCREATEDBR_SERVER_BUSY,		//server busy
	ASKCREATEDBR_OP_TIMES,			//operations too much
	ASKCREATEDBR_FULL,				//max tables full
	ASKCREATEDBR_SAME_NAME,			//same db name
	ASKCREATECHAR_INVALID_NAME,		//invalid db name
	ASKCREATECHAR_INTERNAL_ERROR,	//internal error
};

enum ASKDELETECHAR_RESULT
{
	ASKDELETECHAR_SUCCESS,			//成功
	ASKDELETECHAR_SERVER_BUSY,		//服务器忙，重试
	ASKDELETECHAR_OP_TIMES,			//操作过于频繁
	ASKDELETECHARR_EMPTY,			//没有角色删除
	ASKDELETECHAR_OP_ERROR,			//错误操作流程
	ASKDELETECHAR_NOT_OWNER,		//不是角色的所有者
	ASKDELETECHAR_INTERNAL_ERROR,	//内部错误
	ASKDELETECHAR_ONLINE,			//角色在线
};

enum PACKET_RET_FLAG
{
	PRF_FAIL  = 0 ,
	PRF_SUCCESS ,
};

#endif