#ifndef _RESULT_DEFINE_H_
#define _RESULT_DEFINE_H_

enum LOGIN_RESULT
{
	LOGINR_SUCCESS = 1,			//
	LOGINR_AUTH_FAIL,			//验证失败
	LOGINR_VERSION_FAIL,		//版本错误
	LOGINR_STOP_SERVICE,		//暂时停止服务
	LOGINCR_FULL,				//Login满
	LOGINCR_STOP_SERVICE,		//暂时停止服务
};

enum DB_OPERATION_TYPE
{
	DB_OPERATION_TYPE_NONE = 0,
	DB_OPERATION_TYPE_CREATE,			
	DB_OPERATION_TYPE_DELETE,
};

enum ASKDBOPERATION_RESULT
{
	ASK_DB_OPERATION_R_SUCCESS,			//
	ASK_DB_OPERATION_R_SERVER_BUSY,		//server busy
	ASK_DB_OPERATION_R_OP_TIMES,		//operations too much
	ASK_DB_OPERATION_R_DB_FULL,			//max tables full
	ASK_DB_OPERATION_R_SAME_DB_NAME,	//same db name
	ASK_DB_OPERATION_R_INVALID_NAME,	//invalid db name
	ASK_DB_OPERATION_R_INTERNAL_ERROR,	//internal error
};

enum PACKET_RET_FLAG
{
	PRF_FAIL  = 0 ,
	PRF_SUCCESS ,
};

#endif